services:
  - type: web
    name: churn-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn churn_api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: churn-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 8501 --server.enableCORS false
    envVars:
      - key: PORT
        value: 8501
